name: Deploy

on:
  workflow_dispatch:

permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout
jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.x' 

      - name: Install .Net AOT ARM64 build toolchain
        run: |
          sudo dpkg --add-architecture arm64 
          sudo bash -c 'cat > /etc/apt/sources.list.d/arm64.list <<EOF
          deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports/ jammy main restricted
          deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports/ jammy-updates main restricted
          deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports/ jammy-backports main restricted universe multiverse
          EOF'
          sudo sed -i -e 's/deb http/deb [arch=amd64] http/g' /etc/apt/sources.list
          sudo sed -i -e 's/deb mirror/deb [arch=amd64] mirror/g' /etc/apt/sources.list
          apt list --upgradable
          sudo apt update
          sudo apt install -y libc6
          sudo apt install -y clang
          sudo apt install -y llvm binutils-aarch64-linux-gnu 
          sudo apt install -y gcc-aarch64-linux-gnu 

      - name: Install zlib1g
        run: sudo apt install -y zlib1g-dev:arm64

      - name: Build AddEditBook Function
        run: dotnet publish -c Release -r linux-arm64 ./BooksApiNative.Functions.AddEditBook

      - name: Build DeleteBook Function
        run: dotnet publish -c Release -r linux-arm64 ./BooksApiNative.Functions.DeleteBook

      - name: Build GetBook Function
        run: dotnet publish -c Release -r linux-arm64 ./BooksApiNative.Functions.GetBook

      - name: Build GetBooks Function
        run: dotnet publish -c Release -r linux-arm64 ./BooksApiNative.Functions.GetBooks

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
          role-session-name: DeployLambda
          aws-region: eu-north-1

      - name: Install CDK
        run: |
          npm install -g typescript
          npm install -g ts-node
          sudo npm install -g aws-cdk

      - name: CDK Deploy
        run: |
          cd deploy
          yarn install
          yarn build
          yarn cdk deploy --parameters LambdaArchitecture=arm64 --require-approval never